# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1d07bebd30dbd34df3259b40dfceda0733215505588c23c5a4f269095a1486c5ba269f96313d361b227c3762880417e6523840789213cdce11cb5628ddeef5

test:
  secret_key_base: 40620a7d9f76d1de582ec1aaa7228de4d53c92d1f9d3c3f371f9de3fc12265fd743cf4a477d7ab0128d62e3347ea8fd29000ca81513755a13112b48654c28d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
